PKG_NAME=uLAPack
PKG_URL=https://github.com/SargisYonan/uLAPack.git
PKG_VERSION=v1.0
PKG_LICENSE=μLAPack License v1.0

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR)/src -f $(CURDIR)/$(PKG_NAME).mk
