# Test app is called the same as testfolder
APPLICATION ?= tests_$(notdir $(patsubst %/,%,$(CURDIR)))

BOARD ?= native
RIOTBASE ?= /data/riotbuild/RIOT
QUIET ?= 1
DEVELHELP ?= 1

# Enable text output of embUnit
OUTPUT=TEXT

# Add path our own modules and packages (path as seen from test app)
EXTERNAL_MODULE_DIRS += ./../../src
EXTERNAL_PKG_DIRS += ./../../pkg
