PKG_NAME=uKal
PKG_URL=https://github.com/SargisYonan/uKal.git
PKG_VERSION=v1.0.1
PKG_LICENSE=μKal License v1.0

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR)/src -f $(CURDIR)/$(PKG_NAME).mk
